### ISSUE TITLE
[EPIC] Hooks stable

### ISSUE THREAD

**Issue by devceline** [WalletConnect/web3inbox-widget#48]
```[tasklist]
### Hooks stable
- [x] Updated registration: move from `register(onSign)` to new flow with `prepareRegistration` and `register`
- [x] Notification history: remove `getMessageHistory`, implement new notification fetching methods:
- [x] `getNotificationHistory`: get notifications (get `limit` notifications starting after message `startingAfter`
- [x] `pageNotifications`: Implement paging for notifications with the ability for infinite scroll
- [x] Update API in breaking way: Change all returns of hooks to comply with API: `{data, error, isLoading}`:
- [ ] #28
- [ ] https://github.com/WalletConnect/web3inbox-widget/issues/52
- [ ] https://github.com/WalletConnect/web3inbox-widget/issues/53
- [ ] #47
- [ ] https://github.com/WalletConnect/web3inbox-widget/issues/40
- [ ] https://github.com/WalletConnect/web3inbox-widget/issues/45
- [ ] https://github.com/WalletConnect/web3inbox-widget/issues/61
```
